# Generated by Django 5.2.7 on 2025-12-13 19:33

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.common.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="UserRole",
            fields=[
                ("role_id", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=50, unique=True)),
            ],
            options={
                "db_table": "user_role",
            },
        ),
        migrations.CreateModel(
            name="UserAccount",
            fields=[
                ("user_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("password_hash", models.CharField(max_length=100)),
                ("last_login", models.DateTimeField(default=django.utils.timezone.now)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "role",
                    models.ForeignKey(
                        db_column="role_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="account.userrole",
                    ),
                ),
            ],
            options={
                "db_table": "user_account",
            },
        ),
        migrations.CreateModel(
            name="SystemSetting",
            fields=[
                ("setting_id", models.AutoField(primary_key=True, serialize=False)),
                ("key", models.CharField(max_length=100, unique=True)),
                ("value", models.CharField(max_length=255)),
                ("description", models.CharField(max_length=300)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="updated_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="account.useraccount",
                    ),
                ),
            ],
            options={
                "db_table": "system_setting",
                "indexes": [models.Index(fields=["key"], name="system_sett_key_465b7c_idx")],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                ("application_id", models.AutoField(primary_key=True, serialize=False)),
                ("email", models.EmailField(max_length=255, unique=True)),
                ("password_hash", models.CharField(max_length=100)),
                (
                    "application_datetime",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "status",
                    apps.common.fields.PostgreSQLEnumField(
                        default="рассматривается",
                        enum_type="application_status_type",
                        enum_values=["предоставлен", "рассматривается", "отклонён"],
                    ),
                ),
                (
                    "review_comment",
                    models.CharField(blank=True, max_length=500, null=True),
                ),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        db_column="reviewed_by",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="account.useraccount",
                    ),
                ),
            ],
            options={
                "db_table": "application",
                "indexes": [
                    models.Index(fields=["status"], name="application_status_b7b725_idx"),
                    models.Index(
                        fields=["application_datetime"],
                        name="application_applica_a51bd9_idx",
                    ),
                ],
            },
        ),
        migrations.AddIndex(
            model_name="useraccount",
            index=models.Index(fields=["email"], name="user_accoun_email_66c2af_idx"),
        ),
    ]
