# Generated by Django 5.2.7 on 2026-01-11 15:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="useraccount",
            name="token_version",
            field=models.IntegerField(default=0, editable=False),
        ),
    ]
