# Generated by Django 5.2.7 on 2026-01-14 20:27

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_useraccount_token_version"),
        ("account", "0003_create_roles"),
    ]

    operations = []
