# Generated by Django 5.2.7 on 2026-03-19 17:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0004_merge_20260114_2327"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="useraccount",
            name="token_version",
        ),
        migrations.AddField(
            model_name="useraccount",
            name="password_changed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="application",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
