# Generated by Django 5.2.7 on 2026-03-27 16:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_alter_application_reviewed_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="auditlog",
            name="new_values",
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="auditlog",
            name="old_values",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
