# Generated by Django 5.2.7 on 2026-04-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0007_auditlog_new_values_auditlog_old_values"),
    ]

    operations = [
        migrations.AlterField(
            model_name="application",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "Заявка с таким email уже существует"},
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="key",
            field=models.CharField(
                error_messages={"unique": "Настройка с таким ключом уже существует"},
                max_length=100,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "Email уже зарегистрирован"},
                max_length=255,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="name",
            field=models.CharField(
                error_messages={"unique": "Роль с таким названием уже существует"},
                max_length=50,
                unique=True,
            ),
        ),
    ]
