# Generated by Django 5.2.7 on 2026-04-05 08:54

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models

import apps.common.fields


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0008_alter_application_email_alter_systemsetting_key_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="application",
            options={"verbose_name": "заявка", "verbose_name_plural": "заявки"},
        ),
        migrations.AlterModelOptions(
            name="auditlog",
            options={
                "verbose_name": "лог аудита",
                "verbose_name_plural": "логи аудита",
            },
        ),
        migrations.AlterModelOptions(
            name="systemsetting",
            options={
                "verbose_name": "настройка системы",
                "verbose_name_plural": "настройки системы",
            },
        ),
        migrations.AlterModelOptions(
            name="useraccount",
            options={
                "verbose_name": "учётная запись",
                "verbose_name_plural": "учётные записи",
            },
        ),
        migrations.AlterModelOptions(
            name="userrole",
            options={
                "verbose_name": "роль пользователя",
                "verbose_name_plural": "роли пользователей",
            },
        ),
        migrations.AlterField(
            model_name="application",
            name="application_datetime",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Дата заявки"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="application_id",
            field=models.AutoField(primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="application",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "Заявка с таким email уже существует"},
                max_length=255,
                unique=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="password_hash",
            field=models.CharField(max_length=100, verbose_name="Хеш пароля"),
        ),
        migrations.AlterField(
            model_name="application",
            name="review_comment",
            field=models.CharField(
                blank=True, max_length=500, null=True, verbose_name="Комментарий"
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="reviewed_by",
            field=models.ForeignKey(
                blank=True,
                db_column="reviewed_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="reviewed_applications",
                to="account.useraccount",
                verbose_name="Рассмотрел",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="status",
            field=apps.common.fields.PostgreSQLEnumField(
                default="рассматривается",
                enum_type="application_status_type",
                enum_values=["предоставлен", "рассматривается", "отклонён"],
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="application",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="action",
            field=models.CharField(max_length=50, verbose_name="Действие"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="ip_address",
            field=models.GenericIPAddressField(blank=True, null=True, verbose_name="IP-адрес"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="log_id",
            field=models.BigAutoField(primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="model_name",
            field=models.CharField(max_length=100, verbose_name="Модель"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="new_values",
            field=models.JSONField(blank=True, null=True, verbose_name="Новые значения"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="object_id",
            field=models.IntegerField(blank=True, null=True, verbose_name="ID объекта"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="old_values",
            field=models.JSONField(blank=True, null=True, verbose_name="Старые значения"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="request_data",
            field=models.JSONField(blank=True, null=True, verbose_name="Данные запроса"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="timestamp",
            field=models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Время"),
        ),
        migrations.AlterField(
            model_name="auditlog",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="audit_logs",
                to="account.useraccount",
                verbose_name="Пользователь",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="description",
            field=models.CharField(max_length=300, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="key",
            field=models.CharField(
                error_messages={"unique": "Настройка с таким ключом уже существует"},
                max_length=100,
                unique=True,
                verbose_name="Ключ",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="setting_id",
            field=models.AutoField(primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="updated_by",
            field=models.ForeignKey(
                blank=True,
                db_column="updated_by",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="updated_settings",
                to="account.useraccount",
                verbose_name="Обновил",
            ),
        ),
        migrations.AlterField(
            model_name="systemsetting",
            name="value",
            field=models.CharField(max_length=255, verbose_name="Значение"),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Создан"),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="email",
            field=models.EmailField(
                error_messages={"unique": "Email уже зарегистрирован"},
                max_length=255,
                unique=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="Активен"),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="last_login",
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name="Последний вход"
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="password_changed_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Смена пароля"),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="password_hash",
            field=models.CharField(max_length=100, verbose_name="Хеш пароля"),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="role",
            field=models.ForeignKey(
                db_column="role_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                to="account.userrole",
                verbose_name="Роль",
            ),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Обновлён"),
        ),
        migrations.AlterField(
            model_name="useraccount",
            name="user_id",
            field=models.AutoField(primary_key=True, serialize=False, verbose_name="ID"),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="name",
            field=models.CharField(
                error_messages={"unique": "Роль с таким названием уже существует"},
                max_length=50,
                unique=True,
                verbose_name="Название",
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="role_id",
            field=models.AutoField(primary_key=True, serialize=False, verbose_name="ID"),
        ),
    ]
