[mypy]
show_error_codes = True
plugins = mypy_django_plugin.main, mypy_drf_plugin.main
mypy_path = .

[mypy-*.migrations.*]
ignore_errors = True

[mypy-django.*]
ignore_missing_imports = True

[mypy-rest_framework.*]
ignore_missing_imports = True

[mypy-django_filters.*]
ignore_missing_imports = True

[mypy-ipware.*]
ignore_missing_imports = True

[mypy-user_agents.*]
ignore_missing_imports = True

[mypy-decouple.*]
ignore_missing_imports = True

[mypy-redis.*]
ignore_errors = True

[mypy-django_redis.*]
ignore_missing_imports = True

[mypy-rest_framework_simplejwt.*]
ignore_errors = True

[mypy-drf_yasg]
ignore_missing_imports = True

[mypy-debug_toolbar]
ignore_missing_imports = True

[mypy.plugins.django-stubs]
django_settings_module = config.settings
