# Generated by Django 5.2.7 on 2025-12-13 19:33

import datetime

import django.db.models.deletion
from django.db import migrations, models

import apps.common.fields


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Municipality",
            fields=[
                (
                    "municipality_id",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("name", models.CharField(max_length=150)),
            ],
            options={
                "db_table": "municipality",
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                ("subject_id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=100)),
                ("short_name", models.CharField(max_length=10)),
            ],
            options={
                "db_table": "subject",
            },
        ),
        migrations.CreateModel(
            name="EducationInstitution",
            fields=[
                ("institution_id", models.AutoField(primary_key=True, serialize=False)),
                ("full_name", models.CharField(max_length=500)),
                ("short_name", models.CharField(max_length=300)),
                (
                    "municipality",
                    models.ForeignKey(
                        db_column="municipality_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="vsosh.municipality",
                    ),
                ),
            ],
            options={
                "db_table": "education_institution",
            },
        ),
        migrations.CreateModel(
            name="Participant",
            fields=[
                ("participant_id", models.AutoField(primary_key=True, serialize=False)),
                ("lastname", models.CharField(max_length=150)),
                ("firstname", models.CharField(max_length=150)),
                ("patronymic", models.CharField(blank=True, max_length=150, null=True)),
                ("birth_date", models.DateField()),
                (
                    "gender",
                    apps.common.fields.PostgreSQLEnumField(
                        default="М", enum_type="gender_type", enum_values=["М", "Ж"]
                    ),
                ),
            ],
            options={
                "db_table": "participant",
                "indexes": [
                    models.Index(
                        fields=["lastname", "firstname", "patronymic"],
                        name="participant_lastnam_0e396f_idx",
                    )
                ],
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(
                            (
                                "birth_date__range",
                                (
                                    datetime.date(1950, 1, 1),
                                    datetime.date(2025, 12, 13),
                                ),
                            )
                        ),
                        name="birth_date_check",
                        violation_error_code="Дата рождения невалидна!",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="OlympiadParticipation",
            fields=[
                ("olymp_id", models.AutoField(primary_key=True, serialize=False)),
                ("class_field", models.SmallIntegerField(db_column="class")),
                (
                    "stage",
                    apps.common.fields.PostgreSQLEnumField(
                        enum_type="stage_type", enum_values=["ШЭ", "МЭ", "РЭ", "ЗЭ"]
                    ),
                ),
                (
                    "status",
                    apps.common.fields.PostgreSQLEnumField(
                        enum_type="participation_status_type",
                        enum_values=["победитель", "призёр", "участник"],
                    ),
                ),
                ("year", models.SmallIntegerField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now_add=True)),
                (
                    "education",
                    models.ForeignKey(
                        db_column="education_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="vsosh.educationinstitution",
                    ),
                ),
                (
                    "participant",
                    models.ForeignKey(
                        db_column="participant_id",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="vsosh.participant",
                    ),
                ),
                (
                    "subject",
                    models.ForeignKey(
                        db_column="subject_id",
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="vsosh.subject",
                    ),
                ),
            ],
            options={
                "db_table": "olympiad_participation",
            },
        ),
        migrations.AddIndex(
            model_name="educationinstitution",
            index=models.Index(fields=["municipality"], name="education_i_municip_d80d80_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="educationinstitution",
            unique_together={("municipality", "full_name")},
        ),
        migrations.AddIndex(
            model_name="olympiadparticipation",
            index=models.Index(fields=["participant"], name="olympiad_pa_partici_bfa333_idx"),
        ),
        migrations.AddIndex(
            model_name="olympiadparticipation",
            index=models.Index(fields=["stage", "status"], name="olympiad_pa_stage_308cc7_idx"),
        ),
        migrations.AddIndex(
            model_name="olympiadparticipation",
            index=models.Index(fields=["subject"], name="olympiad_pa_subject_e54dc2_idx"),
        ),
        migrations.AddIndex(
            model_name="olympiadparticipation",
            index=models.Index(fields=["education"], name="olympiad_pa_educati_f83a6b_idx"),
        ),
        migrations.AddIndex(
            model_name="olympiadparticipation",
            index=models.Index(fields=["year"], name="olympiad_pa_year_3a5176_idx"),
        ),
        migrations.AddConstraint(
            model_name="olympiadparticipation",
            constraint=models.CheckConstraint(
                condition=models.Q(("class_field__range", (1, 11))),
                name="class_check",
                violation_error_code="Такого класса не существует!",
            ),
        ),
        migrations.AddConstraint(
            model_name="olympiadparticipation",
            constraint=models.CheckConstraint(
                condition=models.Q(("year__range", (1960, 2026))),
                name="year_check",
                violation_error_code="Год не валиден!",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="olympiadparticipation",
            unique_together={("participant", "subject", "stage", "year")},
        ),
    ]
