# Generated by Django 5.2.7 on 2026-01-11 15:19

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vsosh", "0001_initial"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="olympiadparticipation",
            name="year_check",
        ),
        migrations.RemoveConstraint(
            model_name="participant",
            name="birth_date_check",
        ),
        migrations.AddConstraint(
            model_name="olympiadparticipation",
            constraint=models.CheckConstraint(
                condition=models.Q(("year__range", (1960, 2027))),
                name="year_check",
                violation_error_code="Год не валиден!",
            ),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    (
                        "birth_date__range",
                        (datetime.date(1950, 1, 1), datetime.date(2026, 1, 11)),
                    )
                ),
                name="birth_date_check",
                violation_error_code="Дата рождения невалидна!",
            ),
        ),
    ]
