# Generated by Django 5.2.7 on 2026-01-14 20:52

import datetime

import django.db.models.expressions
from django.db import migrations, models

import apps.vsosh.models


class Migration(migrations.Migration):
    dependencies = [
        ("vsosh", "0002_remove_olympiadparticipation_year_check_and_more"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="olympiadparticipation",
            name="year_check",
        ),
        migrations.RemoveConstraint(
            model_name="participant",
            name="birth_date_check",
        ),
        migrations.AddConstraint(
            model_name="olympiadparticipation",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("year__gte", 1960),
                    (
                        "year__lte",
                        django.db.models.expressions.CombinedExpression(
                            apps.vsosh.models.CurrentYear(), "+", models.Value(1)
                        ),
                    ),
                ),
                name="year_check",
                violation_error_message="Некорректный год олимпиады. Допустимый диапазон: с 1960 года по следующий за текущим.",
            ),
        ),
        migrations.AddConstraint(
            model_name="participant",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("birth_date__gte", datetime.date(1950, 1, 1)),
                    ("birth_date__lte", apps.vsosh.models.CurrentDate()),
                ),
                name="birth_date_check",
                violation_error_code="Некорректная дата рождения. Укажите дату с 1950 года по текущую.",
            ),
        ),
        migrations.AlterConstraint(
            model_name="olympiadparticipation",
            name="class_check",
            constraint=models.CheckConstraint(
                condition=models.Q(("class_field__range", (1, 11))),
                name="class_check",
                violation_error_message="Некорректный класс. Допустимые значения: от 1 до 11.",
            ),
        ),
    ]
