# Generated by Django 5.2.7 on 2026-02-22 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vsosh", "0003_remove_olympiadparticipation_year_check_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationinstitution",
            name="municipality",
            field=models.ForeignKey(
                db_column="municipality_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="education_institutions",
                to="vsosh.municipality",
            ),
        ),
        migrations.AlterField(
            model_name="olympiadparticipation",
            name="education",
            field=models.ForeignKey(
                db_column="education_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="olympiad_participations",
                to="vsosh.educationinstitution",
            ),
        ),
        migrations.AlterField(
            model_name="olympiadparticipation",
            name="participant",
            field=models.ForeignKey(
                db_column="participant_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="olympiad_participations",
                to="vsosh.participant",
            ),
        ),
        migrations.AlterField(
            model_name="olympiadparticipation",
            name="subject",
            field=models.ForeignKey(
                db_column="subject_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="olympiad_participations",
                to="vsosh.subject",
            ),
        ),
        migrations.AlterField(
            model_name="olympiadparticipation",
            name="updated_at",
            field=models.DateTimeField(),
        ),
    ]
