# Generated by Django 5.2.7 on 2026-03-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vsosh", "0004_alter_educationinstitution_municipality_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="olympiadparticipation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
