# Generated by Django 5.2.7 on 2026-04-04 10:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vsosh", "0005_alter_olympiadparticipation_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="municipality",
            name="name",
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="full_name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="subject",
            name="short_name",
            field=models.CharField(max_length=25, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name="educationinstitution",
            unique_together={
                ("municipality", "full_name"),
                ("municipality", "short_name"),
            },
        ),
    ]
