# Generated by Django 5.2.7 on 2026-04-04 15:59

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("vsosh", "0006_alter_municipality_name_alter_subject_full_name_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="educationinstitution",
            options={
                "verbose_name": "образовательное учреждение",
                "verbose_name_plural": "образовательные учреждения",
            },
        ),
        migrations.AlterModelOptions(
            name="municipality",
            options={
                "verbose_name": "муниципалитет",
                "verbose_name_plural": "муниципалитеты",
            },
        ),
        migrations.AlterModelOptions(
            name="olympiadparticipation",
            options={
                "verbose_name": "участие в олимпиаде",
                "verbose_name_plural": "участия в олимпиадах",
            },
        ),
        migrations.AlterModelOptions(
            name="participant",
            options={"verbose_name": "участник", "verbose_name_plural": "участники"},
        ),
        migrations.AlterModelOptions(
            name="subject",
            options={"verbose_name": "предмет", "verbose_name_plural": "предметы"},
        ),
        migrations.AlterUniqueTogether(
            name="educationinstitution",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="name",
            field=models.CharField(max_length=150),
        ),
        migrations.AlterField(
            model_name="subject",
            name="full_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="subject",
            name="short_name",
            field=models.CharField(max_length=25),
        ),
        migrations.AddConstraint(
            model_name="educationinstitution",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("full_name"),
                models.F("municipality"),
                name="unique_edu_full_name_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="educationinstitution",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("short_name"),
                models.F("municipality"),
                name="unique_edu_short_name_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="municipality",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("name"),
                name="unique_municipality_name_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("full_name"),
                name="unique_subject_full_name_ci",
            ),
        ),
        migrations.AddConstraint(
            model_name="subject",
            constraint=models.UniqueConstraint(
                django.db.models.functions.text.Lower("short_name"),
                name="unique_subject_short_name_ci",
            ),
        ),
    ]
