# Generated by Django 5.2.7 on 2026-04-05 08:54

import django.db.models.deletion
from django.db import migrations, models

import apps.common.fields


class Migration(migrations.Migration):
    dependencies = [
        ("vsosh", "0007_alter_educationinstitution_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationinstitution",
            name="full_name",
            field=models.CharField(max_length=500, verbose_name="Полное наименование"),
        ),
        migrations.AlterField(
            model_name="educationinstitution",
            name="municipality",
            field=models.ForeignKey(
                db_column="municipality_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="education_institutions",
                to="vsosh.municipality",
                verbose_name="Муниципалитет",
            ),
        ),
        migrations.AlterField(
            model_name="educationinstitution",
            name="short_name",
            field=models.CharField(max_length=300, verbose_name="Краткое наименование"),
        ),
        migrations.AlterField(
            model_name="municipality",
            name="name",
            field=models.CharField(max_length=150, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="olympiadparticipation",
            name="class_field",
            field=models.SmallIntegerField(db_column="class", verbose_name="Класс"),
        ),
        migrations.AlterField(
            model_name="olympiadparticipation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, verbose_name="Дата создания"),
        ),
        migrations.AlterField(
            model_name="olympiadparticipation",
            name="education",
            field=models.ForeignKey(
                db_column="education_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="olympiad_participations",
                to="vsosh.educationinstitution",
                verbose_name="Образовательное учреждение",
            ),
        ),
        migrations.AlterField(
            model_name="olympiadparticipation",
            name="participant",
            field=models.ForeignKey(
                db_column="participant_id",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="olympiad_participations",
                to="vsosh.participant",
                verbose_name="Участник",
            ),
        ),
        migrations.AlterField(
            model_name="olympiadparticipation",
            name="stage",
            field=apps.common.fields.PostgreSQLEnumField(
                enum_type="stage_type",
                enum_values=["ШЭ", "МЭ", "РЭ", "ЗЭ"],
                verbose_name="Этап",
            ),
        ),
        migrations.AlterField(
            model_name="olympiadparticipation",
            name="status",
            field=apps.common.fields.PostgreSQLEnumField(
                enum_type="participation_status_type",
                enum_values=["победитель", "призёр", "участник"],
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="olympiadparticipation",
            name="subject",
            field=models.ForeignKey(
                db_column="subject_id",
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="olympiad_participations",
                to="vsosh.subject",
                verbose_name="Предмет",
            ),
        ),
        migrations.AlterField(
            model_name="olympiadparticipation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
        ),
        migrations.AlterField(
            model_name="olympiadparticipation",
            name="year",
            field=models.SmallIntegerField(verbose_name="Год"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="birth_date",
            field=models.DateField(verbose_name="Дата рождения"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="firstname",
            field=models.CharField(max_length=150, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="gender",
            field=apps.common.fields.PostgreSQLEnumField(
                default="М",
                enum_type="gender_type",
                enum_values=["М", "Ж"],
                verbose_name="Пол",
            ),
        ),
        migrations.AlterField(
            model_name="participant",
            name="lastname",
            field=models.CharField(max_length=150, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="participant",
            name="patronymic",
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name="Отчество"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="full_name",
            field=models.CharField(max_length=100, verbose_name="Полное название"),
        ),
        migrations.AlterField(
            model_name="subject",
            name="short_name",
            field=models.CharField(max_length=25, verbose_name="Краткое название"),
        ),
    ]
